# Generated by Django 3.1.7 on 2021-07-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('owner_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('telephone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('pet_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('bday', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.owners')),
            ],
            options={
                'db_table': 'Pets',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('spec_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Specialties',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Vets',
            fields=[
                ('vet_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Vets',
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('visit_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.pets')),
            ],
            options={
                'db_table': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='VetSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.specialties')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.vets')),
            ],
            options={
                'db_table': 'VetSpec',
            },
        ),
        migrations.AddField(
            model_name='pets',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.types'),
        ),
    ]
