# Generated by Django 3.1.7 on 2021-06-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.owners')),
            ],
        ),
    ]
